services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vacancies
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: